### ISSUE TITLE
upload firmware failed with local LVFS Website

### ISSUE THREAD

**Issue by hpo14** [fwupd/lvfs-website#797]
Hi

It's really hard for me to figured out the whole process for setting up a private LVFS website
I am success running a local LVFS website but the exception happened when upload firmware.

OS Environment: Ubuntu 16.04 64bit
Python Version: python 3.7
LVFS version: tag-1.2.0

I running a local LVFS with Below steps:
1. Running postgreSQL and redis with container
2. create PostgreSQL database manually
```
$ psql
> CREATE USER test WITH PASSWORD 'test';
> CREATE DATABASE lvfs OWNER test;
> quit
```
```
FLASK_APP=lvfs/__init__.py ./env/bin/flask initdb
FLASK_APP=lvfs/__init__.py ./env/bin/flask db stamp
FLASK_APP=lvfs/__init__.py ./env/bin/flask db upgrade
```
3. running locally server (all required package was installed)
```
python3 -m virtualenv env
source env/bin/activate
pip3 install -r requirements.txt
FLASK_DEBUG=1 ./app.wsgi
```
4. Login website with default admin account and password (``sign-test@fwupd.org`` / ``Pa$$w0rd``)
5. visiting ``http://127.0.0.1:5000/lvfs/settings/create`` to set default settings
6. manually ``Disable`` all setting in settings
7. manually upload a test firmware (which was uploaded to fwupd.org/lvfs and valided)
8. then error happened
```
Traceback (most recent call last):
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user123/Desktop/temp/lvfs-website/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/user123/Desktop/temp/lvfs-website/lvfs/upload/routes.py", line 323, in route_firmware
    return _upload_firmware()
  File "/home/user123/Desktop/temp/lvfs-website/lvfs/upload/routes.py", line 130, in _upload_firmware
    ufile.parse(os.path.basename(fileitem.filename), fileitem.read())
  File "/home/user123/Desktop/temp/lvfs-website/lvfs/upload/uploadedfile.py", line 647, in parse
    self.cabarchive_upload = CabArchive(data, flattern=True)
  File "/home/user123/Desktop/temp/lvfs-website/cabarchive/cabarchive.py", line 40, in __init__
    cfarchive.extract(None)
TypeError: Argument 1 does not allow None as a value
```

For more information from ```make check```, detailed log please check [make_check_result.log](https://pastebin.com/CbjaWtxJ)
``
============= 80 failed, 22 passed, 5 warnings in 98.40s (0:01:38) =============
``

**Comment by hughsie** [comment]
> It's really hard for me to figured out the whole process for setting up a private LVFS website

Back a bit; why are you trying to set up your own instance? If you work for an OEM or ODM I can create you a _test_ account on the actual LVFS if that makes your life easier.

> Ubuntu 16.04 64bit

This is really much too old. It's over 5 years old and a few months away from being completely unsupported by Canonical.

> cfarchive.extract(None)

This is saying that the version of libgcab is too old to support extracting to memory. You need at least gcab 1.0 for this feature; that was released about 3 years ago.

**Comment by hpo14** [comment]
> > It's really hard for me to figured out the whole process for setting up a private LVFS website
> 
> Back a bit; why are you trying to set up your own instance? If you work for an OEM or ODM I can create you a _test_ account on the actual LVFS if that makes your life easier.

For some reason, i need to set up a private LVFS website.
And thank your for serving official LVFS and i already have an account on LVFS.

> 
> > Ubuntu 16.04 64bit
> 
> This is really much too old. It's over 5 years old and a few months away from being completely unsupported by Canonical.

I will try to use a higher version like Ubuntu 18.04. LTS

> 
> > cfarchive.extract(None)
> 
> This is saying that the version of libgcab is too old to support extracting to memory. You need at least gcab 1.0 for this feature; that was released about 3 years ago.

Here is my libgcab version, seems the version is 0.7-1, which is too old as you said.
```
user123) ~/ $ dpkg -l | grep gcab
ii  gcab                                                        0.7-1ubuntu0.1 
ii  gir1.2-libgcab-1.0:amd64                                    0.7-1ubuntu0.1 
ii  libgcab-1.0-0:amd64                                         0.7-1ubuntu0.1 
```

**Comment by superm1** [comment]
> I will try to use a higher version like Ubuntu 18.04. LTS

If you have the opportunity to use a newer version and are in the Ubuntu family of OSes, I would just baseline on Ubuntu 20.04 instead.  You'll get a longer longevity and less problems later if dependencies go up in the future.

Another option for you is to run LVFS within a container, where it's easier to control and get new userspace software.

**Comment by hpo14** [comment]
> > I will try to use a higher version like Ubuntu 18.04. LTS
> 
> If you have the opportunity to use a newer version and are in the Ubuntu family of OSes, I would just baseline on Ubuntu 20.04 instead. You'll get a longer longevity and less problems later if dependencies go up in the future.
> 
> Another option for you is to run LVFS within a container, where it's easier to control and get new userspace software.

Thank for advise.
Yes, ofcourse running LVFS in the container is better then running it on bare matel.
But I want to verify LVFS on bare metal for first, after that i will build into a docker image as your recommendation.
